name: projeto_app_denuncia
description: A Flutter project.
publish_to: 'none'

version: 0.7.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  provider:
  shared_preferences:
  url_launcher:
  http:
  fluttertoast:
  easy_dynamic_theme:
  sqflite:
  jiffy:
  share:
  cupertino_icons: ^1.0.2
  image_picker:
  flutter_native_image:
  location: ^4.4.0
  dynamic_value:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
